### ISSUE TITLE
Azure pytest on python 3.5 fails

### ISSUE THREAD

**Issue by jtmoon79** [jtmoon79/goto_http_redirect_server#30]
python 3.5 pytest running in Azure fails.

From [here](https://dev.azure.com/jtmmoon/goto_http_redirect_server/_build/results?buildId=348&view=logs&j=9a313c73-616a-569c-b856-51b31015f629&t=1681d1dc-3902-54d5-95d8-32294de9fd0e)

```
+ python -m pip install --user -e '.[development-pytest]'
Obtaining file:///home/vsts/work/1/s
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.5.9/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/vsts/work/1/s/setup.py'"'"'; __file__='"'"'/home/vsts/work/1/s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/vsts/work/1/s/
    Complete output (22 lines):
    warning: no files found matching '*.dynlib' under directory 'tests'
    no previously-included directories found matching 'tests/testdata/*/build'
    no previously-included directories found matching 'tests/testdata/*/dist'
    no previously-included directories found matching 'tests/testdata/*/*.egg-info'
    warning: install_lib: 'build/lib' does not exist -- no Python modules to install
    
    zip_safe flag not set; analyzing archive contents...
    
    Installed /home/vsts/work/1/s/.eggs/UNKNOWN-0.0.0-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vsts/work/1/s/setup.py", line 267, in <module>
        include_package_data=True,
      File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/pkg_resources/__init__.py", line 853, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'wheel' distribution was not found and is required by the application
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

##[error]Bash exited with code '1'.
Finishing: task: «Bash@3» Python 3.5

```

Notable error `pkg_resources.DistributionNotFound: The 'wheel' distribution was not found and is required by the application`.

The `.azure-pipelines/azure-pipelines.yml` has effective code
```
      - job: job_pytest
        displayName: 'job: «pytest»'
        strategy:
          matrix:
            Python35:
              python.release: '3.5'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: Bash@3
            displayName: 'task: «Bash@3» Python $(python.release)'
            inputs:
              targetType: inline
              script: |
                set -eux
                python --version
                python -m pip install --user -e '.[development-pytest]'
```
The `'.[development-pytest]'` is from [`setup.py` entry](https://github.com/jtmoon79/goto_http_redirect_server/blob/9f17f945598ac39ba4157be49aba806ae3acf529/setup.py#L221-L225):
```
        'development-pytest': [
            'pytest',
            'pytest-cov',
            'pytest-timeout',
        ],
```

Pytest using Python 3.7 or Python 3.6 succeeds.

**Comment by jtmoon79** [comment]
For the time being, pytest on python 3.5 is commented out.  fa44a5b4f73fb5742429fd23c0bebb189bcc1a09

**Comment by jtmoon79** [comment]
Python 3.5 support was removed.
